version: "3.8"

services:

  nginx:
    image: public.ecr.aws/s3y9y4j4/nginx:latest
    ports:
      - 443:443
    links:
      - api
    volumes:
      - ./others/nginx/certs/privkey.pem:/etc/nginx/privkey.pem
      - ./others/nginx/certs/fullchain.pem:/etc/nginx/fullchain.pem

  api:
    image: public.ecr.aws/s3y9y4j4/mindhub-api:latest
    env_file:
      - ./nest/.env

  providers-sync:
    image: public.ecr.aws/s3y9y4j4/mindhub-providers-sync:latest
    env_file:
      - ./nest/.env

  frs:
    image: public.ecr.aws/s3y9y4j4/mindhub-frs:latest
    stdin_open: true
    tty: true
    env_file:
      - ./frs/.env

  apr:
    image: public.ecr.aws/s3y9y4j4/mindhub-apr:latest
    stdin_open: true
    tty: true
    env_file:
      - ./apr/.env

  chatbot:
    image: public.ecr.aws/s3y9y4j4/mindhub-chatbot:latest
    stdin_open: true
    tty: true
    env_file:
      - ./others/chatbot/.env
  