version: "3.8"

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - api
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  api:
    build:
      dockerfile: apps/api-app/Dockerfile
      context: nest/
    env_file:
      - ./nest/.env

  providers-sync:
    build:
      dockerfile: apps/providers-sync-app/Dockerfile
      context: nest/
    env_file:
      - ./nest/.env
