service: mindhub
frameworkVersion: '3'

custom:
  cognito:
    userPoolArn: arn:aws:cognito-idp:us-east-1:598854603683:userpool/us-east-1_ACYhVKPRs

  dynamo:
    usersTable: 'users-table'
    friendshipsTable: 'friendships-table'

    # TODO: Move to other app
    providerTokens: 'provider-tokens-table'
    resourcesTable: 'resources-table'
    interestsTable: 'interests-table'
  
  s3:
    picturesBucket: 'mindhub-pictures-bucket'
    pictureUploadUrlTTL: 60
    pictureDownloadUrlTTL: 60
    allowedOrigins: 'https://mindhub.ar'

  ses:
    friendshipRequestsMailSender: 'notifications@mindhub.ar'

  sqs:
    providerSyncQueue:
      name: 'provider-sync-queue'
      dltName: 'provider-sync-dlt-queue'
      maxRetries: 5
      visibilityTimeoutSecs: 30
  
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: [aws-sdk]
    target: node18
    define: 'require.resolve: undefined'
    platform: node
    concurrency: 10

  serverless-dynamodb:
    start:
      port: 8000
      docker: false
      migrate: true
    stages: dev

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
      shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
        - Effect: Allow
          Action:
            - s3:putObjectAcl
          Resource:
            - Fn::GetAtt: [ PicturesBucket, Arn ]
          
  environment:
    USERS_POOL_ID: us-east-1_ACYhVKPRs

    DYNAMO_USERS_TABLE: ${self:custom.dynamo.usersTable}
    DYNAMO_FRIENDSHIPS_TABLE: ${self:custom.dynamo.friendshipsTable}

    # TODO: Move to other app
    DYNAMO_PROVIDER_TOKENS_TABLE: ${self:custom.dynamo.providerTokens}
    DYNAMO_RESOURCES_TABLE: ${self:custom.dynamo.resourcesTable}
    DYNAMO_INTERESTS_TABLE: ${self:custom.dynamo.interestsTable}

    S3_PICTURES_BUCKET: ${self:custom.s3.picturesBucket}
    S3_PICTURE_UPLOAD_URL_TTL: ${self:custom.s3.pictureUploadUrlTTL}
    S3_PICTURE_DOWNLOAD_URL_TTL: ${self:custom.s3.pictureDownloadUrlTTL}

    FRIENDSHIP_REQUESTS_SENDER_EMAIL: ${self:custom.ses.friendshipRequestsMailSender}

    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

# functions:
#   app: 
#     handler: dist/main.handler
#     events:
#       - http:
#           method: any
#           path: /{any+}
#           cors: true
#           integration: lambda-proxy
#           authorizer:
#             name: PrivateAuthorizer
#             type: COGNITO_USER_POOLS
#             arn: ${self:custom.cognito.userPoolArn}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo.usersTable}
        AttributeDefinitions: 
          - AttributeName: _id
            AttributeType: S
        KeySchema: 
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    FriendshipsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo.friendshipsTable}
        AttributeDefinitions:
          - AttributeName: proposer
            AttributeType: S 
          - AttributeName: target
            AttributeType: S
        KeySchema: 
          - AttributeName: proposer
            KeyType: HASH
          - AttributeName: target
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: InvertedIndex
            KeySchema:
              - AttributeName: target
                KeyType: HASH
              - AttributeName: proposer
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    PicturesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mindhub-pictures-bucket
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - ${self:custom.s3.allowedOrigins}

    ProviderTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo.providerTokens}
        AttributeDefinitions: 
          - AttributeName: userId
            AttributeType: S
          - AttributeName: service
            AttributeType: S
        KeySchema: 
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: service
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # TODO: Move to other app
    
    ResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo.resourcesTable}
        AttributeDefinitions:
          - AttributeName: resourceId
            AttributeType: S 
        KeySchema: 
          - AttributeName: resourceId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    InterestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamo.interestsTable}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S 
          - AttributeName: resourceId
            AttributeType: S
        KeySchema: 
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: resourceId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ProviderSyncQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: ${self:custom.sqs.providerSyncQueue.name}
        ReceiveMessageWaitTimeSeconds: 20 # Long polling
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [ ProviderSyncDLTQueue, Arn ]
          maxReceiveCount: ${self:custom.sqs.providerSyncQueue.maxRetries}
        VisibilityTimeout: ${self:custom.sqs.providerSyncQueue.visibilityTimeoutSecs}

    ProviderSyncDLTQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: ${self:custom.sqs.providerSyncQueue.dltName}
        ReceiveMessageWaitTimeSeconds: 20 # Long polling
        # TODO: Circular dependency, by the moment allow all
        # RedriveAllowPolicy:
        #   redrivePermission: byQueue
        #   sourceQueueArns:
        #     - Fn::GetAtt: [ ProviderSyncQueue, Arn ]
    
plugins:
  - serverless-offline
  - serverless-dynamodb

package:
  patterns:
    - "!*"
    - "!*/**"
    - "node_modules/**"
    - "dist/**"
