AWSTemplateFormatVersion: "2010-09-09"

Resources:

  # --------------------------- SQS ---------------------------

  ProviderFileUploadedQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: provider-file-uploaded-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling
      VisibilityTimeout: 30

  ProviderSyncRequestQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: provider-sync-requests-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt ProviderSyncRequestsDLTQueue.Arn
        maxReceiveCount: 5
      VisibilityTimeout: 30

  ProviderSyncRequestsDLTQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: provider-sync-requests-dlt-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling

  PersonalityRequestQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: personality-requests-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt PersonalityRequestDLTQueue.Arn
        maxReceiveCount: 5
      VisibilityTimeout: 30

  PersonalityRequestDLTQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: personality-requests-dlt-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling

  RecommendationRequestQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: recommendation-requests-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt RecommendationRequestDLTQueue.Arn
        maxReceiveCount: 5
      VisibilityTimeout: 30

  RecommendationRequestDLTQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: recommendation-requests-dlt-queue
      ReceiveMessageWaitTimeSeconds: 20 # Long polling

Outputs:
  ProviderFileUploadedQueueURL:
    Value:
      !Ref ProviderFileUploadedQueue
    Export:
      Name:
        !Sub "${AWS::StackName}-ProviderFileUploadedQueueURL"

  ProviderFileUploadedQueueARN:
    Value:
      !GetAtt ProviderFileUploadedQueue.Arn
    Export:
      Name:
        !Sub "${AWS::StackName}-ProviderFileUploadedQueueARN"

  ProviderSyncRequestQueueARN:
    Value:
      !GetAtt ProviderSyncRequestQueue.Arn
    Export:
      Name:
        !Sub "${AWS::StackName}-ProviderSyncRequestQueueARN"

  ProviderSyncRequestQueueURL:
    Value:
      !Ref ProviderSyncRequestQueue
    Export:
      Name:
        !Sub "${AWS::StackName}-ProviderSyncRequestQueueURL"

  PersonalityRequestQueueARN:
    Value:
      !GetAtt PersonalityRequestQueue.Arn
    Export:
      Name:
        !Sub "${AWS::StackName}-PersonalityRequestQueueARN"

  PersonalityRequestQueueURL:
    Value:
      !Ref PersonalityRequestQueue
    Export:
      Name:
        !Sub "${AWS::StackName}-PersonalityRequestQueueURL"

  RecommendationRequestQueueARN:
    Value:
      !GetAtt RecommendationRequestQueue.Arn
    Export:
      Name:
        !Sub "${AWS::StackName}-RecommendationRequestQueueARN"

  RecommendationRequestQueueURL:
    Value:
      !Ref RecommendationRequestQueue
    Export:
      Name:
        !Sub "${AWS::StackName}-RecommendationRequestQueueURL"