version: "3.8"

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - api
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  api:
    # build:
    #   context: ../
    image: mindhub-api
    env_file:
      - ../.env
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s