AWSTemplateFormatVersion: 2010-09-09

Description: The template used to create an ECS Service from the ECS Console.

Parameters:
  ECSClusterName:
    Type: String
    Default: main-cluster
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Default: sg-0450a2e73c8b27ceb
  SubnetIDs:
    Type: CommaDelimitedList
    Default: subnet-0839aa1f99f036c22
  VpcID:
    Type: String
    Default: vpc-0462bb302f13a7a46
  LoadBalancerName:
    Type: String
    Default: mindhub-lb

Resources:

  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: main-cluster
      TaskDefinition: 'arn:aws:ecs:us-east-1:598854603683:task-definition/mindhub-api:6'
      LaunchType: FARGATE
      ServiceName: mindhub-api-service
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      EnableECSManagedTags: true

      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          LoadBalancerName: !Ref 'AWS::NoValue'
          TargetGroupArn: !Ref TargetGroup
      
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIDs
          Subnets: !Ref SubnetIDs
      
      PlatformVersion: LATEST
      
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      
      DeploymentController:
        Type: ECS
      
      ServiceConnectConfiguration:
        Enabled: false
      
    DependsOn:
      - Listener

  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: application
      Name: mindhub-api-lb
      SecurityGroups: !Ref SecurityGroupIDs
      Subnets: !Ref SubnetIDs

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckPath: /health
      Name: mindhub-api-tg
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      VpcId: !Ref VpcID
  
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
  
  AutoScalingTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MaxCapacity: '10'
      MinCapacity: '1'
      ResourceId: service/main-cluster/mindhub-api-service
      RoleARN: >-
        arn:aws:iam::598854603683:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
    DependsOn:
      - ECSService
  
  AutoScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: avg-cpu-utilization-target-policy
      PolicyType: TargetTrackingScaling
      ResourceId: service/main-cluster/mindhub-api-service
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        ScaleInCooldown: '300'
        ScaleOutCooldown: '300'
        TargetValue: '70'
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
  
Outputs:
  ClusterName:
    Description: The cluster used to create the service.
    Value: !Ref ECSClusterName
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
  LoadBalancer:
    Description: The created load balancer.
    Value: !Ref LoadBalancer
  Listener:
    Description: The created listener.
    Value: !Ref Listener
  TargetGroup:
    Description: The created target group.
    Value: !Ref TargetGroup
  AutoScalingTarget:
    Value: !Ref AutoScalingTarget
  AutoScalingPolicy:
    Value: !Ref AutoScalingPolicy
